name: MaSuiteHomes
main: dev.masa.masuitehomes.bukkit.MaSuiteHomes
version: ${project.version}
author: Masagameplay
depend: [MaSuiteCore]
softdepend: [Multiverse, Multiworld]
loadbefore: [Essentials]
api-version: 1.13