name: MaSuiteHomes
main: fi.matiaspaavilainen.masuitehomes.bukkit.MaSuiteHomes
version: ${project.version}
author: Masagameplay
api-version: 1.14
depend: [MaSuiteCore]
softdepend: [Multiverse, Multiworld]